line-length = 120
fix = true

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
line-ending = "lf"
skip-magic-trailing-comma = true

[lint]
select = ["ALL"]

ignore = ["ANN201", "D100", "D101", "D102", "N801", "RUF012"]
